version: '3'

volumes:
  app-cache:
    driver: local

services:
  dalle-backend:
    container_name: dalle-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    volumes:
      - app-cache:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
